### ISSUE TITLE
Clarifications on the Bidding & Auction Services API semantics

### ISSUE THREAD

**Issue by suprajasekhar** [privacysandbox/fledge-docs#10]
Thank you for publishing the [Bidding and Auction Services API](https://github.com/privacysandbox/fledge-docs/blob/main/bidding_auction_services_api.md) proposal. We have summarized a couple of clarifications we are seeking below. Appreciate your inputs.

### Bidding API Semantics

- `BuyerFrontEnd` service returns a single `AdWithBid`. However, a buyer might wish to return multiple bids (for instance, one per each custom audience) since some of their bids may be filtered by the seller's auction due to policy and publisher controls enforcements. Would it be possible to add support for returning multiple bids from the `BuyerFrontEnd`?

- `CustomAudienceForBidding` includes a priority. Who and how will the priority of custom audiences be taken into account?

- In order to support bids for [ads composed of multiple pieces](https://github.com/WICG/turtledove/blob/main/FLEDGE.md#34-ads-composed-of-multiple-pieces), should the `AdWithBid` include URLs of ad components as well (in addition to the `ad_render_url`)?

- Is a buyer’s enrollment ID with Privacy Sandbox the same as the interest group owner origin in the Chrome’s FLEDGE proposal?

### Auction API Semantics

- In FLEDGE proposal, the sellers configure `AuctionConfig` and use it to initiate an auction. However in this proposal, `DeviceSignals` constructed by the device is included in the `AuctionConfig` as well. Will it be structurally cleaner to keep the `DeviceSignals` separate from the `AuctionConfig`?

### Potential Optimizations
> The BuyerFrontEnd service sends a GenerateBids request to the bidding service. The bidding service returns ad candidates with bids.
- Is the `GenerateBids` request executed in a sandbox for a single custom audience or conjointly for all custom audiences originating from a first party advertiser domain? If it is the former, there might be a fixed latency overhead added for every fresh sandbox context as described in [Turtledove Issue 304](https://github.com/WICG/turtledove/issues/304). As we understand it, considering multiple custom audiences from a single domain at the same time, in the same execution context may be compatible with the FLEDGE privacy model.

- In the proposal, the bidding function code is passed to `GenerateBids` in every request as either `js_code` or `wasm_code`. Might it be more efficient to store and precompile the bidding code ahead of time within the bidding service?

While it is great that the proposal is thorough and prescriptive in its API definitions between the client and bidding/auction services, it is not clear what are the incremental changes a buyer or a seller will have to make to their FLEDGE integrations to interact with the proposed bidding and auction services. Would it be possible to summarize the changes required from an ad tech point of view (maybe similar to [these](https://github.com/WICG/turtledove/blob/main/FLEDGE.md#32-on-device-bidding))?

**Comment by chatterjee-priyanka** [comment]
I am closing this since we sought your feedback and incorporated them.
